#!/bin/sh -e



if [ -z $PYGDV_HOME ]; then
    echo 'PYGDV_HOME variable is missing : please add ``export PYGDV_HOME="path/to/pyGDV/project"`` in your environment.'
    exit 1
fi

PYGDV_INI_FILE=$PYGDV_HOME/development_local.ini

case "$1" in
  start)
    paster serve --daemon --pid-file=$PYGDV_HOME/daemon/paster.pid --log-file=$PYGDV_HOME/log/paster.log $PYGDV_INI_FILE start
    ;;
  stop)
    paster serve --daemon --pid-file=$PYGDV_HOME/daemon/paster.pid --log-file=$PYGDV_HOME/log/paster.log  $PYGDV_INI_FILE stop
    ;;
  restart)
    paster serve  --daemon --pid-file=$PYGDV_HOME/daemon/paster.pid --log-file=$PYGDV_HOME/log/paster.log $PYGDV_INI_FILE restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac