#!/bin/sh -e
PYGDV_HOME=/data/pygdv

case "$1" in
  start)
    paster serve --daemon --pid-file=$PYGDV_HOME/paster.pid --log-file=$PYGDV_HOME/paster.log $PYGDV_HOME/production.ini start
    ;;
  stop)
    paster serve --daemon --pid-file=$PYGDV_HOME/paster.pid --log-file=$PYGDV_HOME/paster.log  $PYGDV_HOME/production.ini stop
    ;;
  restart)
    paster serve  --daemon --pid-file=$PYGDV_HOME/paster.pid --log-file=$PYGDV_HOME/paster.log $PYGDV_HOME/production.ini restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac