
NOT_DETERMINED_DATATYPE = 'NOT_DETERMINED'
QUALITATIVE_EXTENDED_DATATYPE = 'QUALITATIVE_EXTENDED'
QUANTITATIVE_DATATYPE = 'QUANTITATIVE'
QUALITATIVE_DATATYPE = 'QUALITATIVE'


date_format = "%A %d. %B %Y %H.%M.%S"



